services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8081:8080"


  maildev:
    image: maildev/maildev
    container_name: dev-maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"


volumes:
  pg_data: