spring:
  #datasource:
  #url: jdbc:postgresql://localhost:5432/blog_db
  #username: postgres
  #password: postgres
  docker:
    compose:
      lifecycle-management: start-and-stop

logging:
  level:
    #root: DEBUG
    org.iamflubin.djetybackend: debug
    #org.springframework: DEBUG
    org.springframework.transaction.interceptor: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace

app:
  security:
    cors:
      allowedOrigins: http://localhost:4200