spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    clean-disabled: true
  docker:
    compose:
      lifecycle-management: none

logging:
  level:
    root: info
    org.iamflubin.djetybackend: info
    org.springframework: info
    org.springframework.jdbc.core.JdbcTemplate: off
    org.springframework.jdbc.core.StatementCreatorUtils: off

app:
  security:
    cors:
      allowedOrigins: ${CORS_ALLOWED_ORIGINS:}