spring:
  application:
    name: backend
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false
    out-of-order: false
    #schemas: public
    #create-schemas: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

server:
  port: 8080
    #servlet:
  #context-path: /api

logging:
  level:
    root: info
    #org.springframework.web: debug
